sudo: required
language: generic 
services:
 - docker

before_install:
 - docker build -t canberksahin/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true canberksahin/docker-react npm run test